footprint: [[0.29, 0.19],
            [-0.29, 0.19],
            [-0.29, -0.19],
            [0.29, -0.19],
            [0.29, -0.11],
            [0.36, -0.11],
            [0.36, 0.11],
            [0.29, 0.11]] 
recovery_behavior_enabled: True
clearing_rotation_allowed: True

controller_frequency: 10.0
controller_patience: 5.0
clearing_radius: 0.25
footprint_padding: 0.1

base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"
#"eband_local_planner/EBandPlannerROS"
